-------------------------------------------------------------------------------
Test set: io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
-------------------------------------------------------------------------------
Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 62.83 s <<< FAILURE! -- in io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testValidation -- Time elapsed: 18.99 s <<< ERROR!
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition s10508240x8a32x49c6x9316x9933e64446e9-0 at offset 30. If needed, please seek past the record to continue consumption.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.consumeMessages(KafkaSerdesTester.java:207)
	at io.apicurio.tests.serdes.apicurio.SimpleSerdesTesterBuilder$SimpleSerdesTester.test(SimpleSerdesTesterBuilder.java:156)
	at io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testValidation(ProtobufSerdeIT.java:193)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing VALUE for partition s10508240x8a32x49c6x9316x9933e64446e9-0 at offset 30. If needed, please seek past the record to continue consumption.
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.newRecordDeserializationException(CompletedFetch.java:346)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:330)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:284)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.fetchRecords(FetchCollector.java:169)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.collectFetch(FetchCollector.java:135)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:146)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.pollForFetches(ClassicKafkaConsumer.java:699)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:623)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at io.apicurio.tests.serdes.apicurio.KafkaSerdesTester.lambda$consumeMessages$5(KafkaSerdesTester.java:179)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:242)
	at io.apicurio.registry.resolver.cache.ERCache.getValue(ERCache.java:173)
	at io.apicurio.registry.resolver.cache.ERCache.getByContentId(ERCache.java:152)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByContentId(DefaultSchemaResolver.java:197)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:171)
	at io.apicurio.registry.serde.AbstractDeserializer.resolve(AbstractDeserializer.java:104)
	at io.apicurio.registry.serde.AbstractDeserializer.readData(AbstractDeserializer.java:93)
	at io.apicurio.registry.serde.KafkaDeserializer.deserialize(KafkaDeserializer.java:46)
	at io.apicurio.registry.serde.protobuf.ProtobufKafkaDeserializer.deserialize(ProtobufKafkaDeserializer.java:55)
	at io.apicurio.registry.serde.protobuf.ProtobufKafkaDeserializer.deserialize(ProtobufKafkaDeserializer.java:14)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:81)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:327)
	... 16 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:437)
	at io.kiota.http.vertx.VertXRequestAdapter.sendCollection(VertXRequestAdapter.java:130)
	at io.apicurio.registry.rest.client.ids.contentids.item.references.ReferencesRequestBuilder.get(ReferencesRequestBuilder.java:53)
	at io.apicurio.registry.rest.client.ids.contentids.item.references.ReferencesRequestBuilder.get(ReferencesRequestBuilder.java:43)
	at io.apicurio.registry.resolver.client.RegistryClientFacadeImpl.getReferencesByContentId(RegistryClientFacadeImpl.java:48)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.lambda$resolveSchemaByContentId$1(DefaultSchemaResolver.java:205)
	at io.apicurio.registry.resolver.cache.ERCache.lambda$getValue$0(ERCache.java:174)
	at io.apicurio.registry.resolver.cache.ERCache.retry(ERCache.java:227)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:431)
	... 34 more
Caused by: io.vertx.core.http.HttpClosedException: Connection was closed

